json.id @goal.id
json.nickname @goal.nickname
json.description @goal.description
json.motivation @goal.motivation
json.impact @goal.impact
json.strategy @goal.strategy
json.deadline @goal.deadline
json.evidence @goal.evidence
json.satisfaction @goal.satisfaction